# actin unsupervised domain adapation pipeline

[run_info]
data_root = "/projects/extern/nhr/nhr_ni/nim00020/dir.project/sage/data"
synthetic_dataset = "deepict_dataset_4"                                     # simulated dataset
real_dataset = "deepict"                                                    # target experimental dataset
run = 14

[prepare_training]
mode = "synthetic"

# synthetic mode
n_conditions = 4
n_tomos = 20
# conditions = [0, 1, 2, 3]             # optional; defaults to range(n_conditions)
train_fraction = 0.7
val_fraction = 0.2
test_fraction = 0.1

# real mode
# sample_mask_dir = "/override/path"    # defaults to {data_root}/experimental/{real_dataset}/sample_masks
# target_voxel_size = 10                # Å; set to 0 to skip rescaling

raw_key = "raw"
label_key = "/labels/actin"
sample_mask_key = "sample_mask"

[supervised_training]
# conditions = [0, 1, 2]               # optional; select a subset of conditions for training
label_key = "/labels/actin"
patch_shape = [64, 256, 256]
batch_size = 4
lr = 4e-4
loss_fn = "CombinedclDiceLoss"         

[domain_adaptation]
# source_checkpoint = "/override/checkpoint/path"
train_glob = "*.h5" #TODO fix this 
val_glob = "*.h5"   #TODO fix this 
raw_key = "raw"
sample_mask_key = "sample_mask"
patch_shape = [64, 256, 256]
batch_size = 2
lr = 2e-4