# actin supervised training pipeline
[run_info]
data_root = "/projects/extern/nhr/nhr_ni/nim00020/dir.project/sage/data"
synthetic_dataset = "deepict_dataset_8"
dataset = "deepict"
run = 33

[prepare_training]
n_conditions = 4
n_tomos = 15
conditions = [0, 1, 2, 3]
train_fraction = 0.7
val_fraction = 0.2
test_fraction = 0.1
raw_key = "raw"
label_key = "/labels/actin"

[supervised_training]
conditions = [0, 1, 2, 3]
label_key = "/labels/actin"
patch_shape = [64, 256, 256]
batch_size = 4
lr = 1e-4
n_iterations = 15_000
save_every_kth_epoch = 2
